[package]
name = "budget1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
chrono-tz = "0.10.1"
clap = { version = "4.5.29", features = ["derive"] }
csv = "1.3.1"
dateparser = "0.2.1"
