// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: number, name: string, account_type: AccountType, statement_schema_id: number | null, };

export type AccountFields = { name: string, account_type: AccountType, statement_schema_id: number | null, };

export type AccountType = "Bank" | "CreditCard" | "Shop" | "Cash";

export type Accounts = { accounts: Array<Account>, };
