// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Budget = { year: number, categories: Array<BudgetCategory>, items: Array<BudgetItem>, };

export type BudgetAmount = { "Weekly": { amount: number, } } | { "Monthly": { amount: number, } } | { "Yearly": { amount: number, } } | { "EveryXYears": { x: number, amount: number, } };

export type BudgetCategory = { id: number, name: string, ignored: boolean, year: number, };

export type BudgetCategoryFields = { name: string, ignored: boolean, year: number, };

export type BudgetItem = { id: number, category_id: number, name: string, amount: BudgetAmount | null, budget_only: boolean, };

export type BudgetItemFields = { category_id: number, name: string, amount: BudgetAmount | null, budget_only: boolean, };
