// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetAmount } from "./BudgetAmount";

export type BudgetItem = { id: number, category_id: number, name: string, amount: BudgetAmount, };
