// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Budget = { year: number, categories: Array<BudgetCategory>, items: Array<BudgetItem>, };

export type BudgetAmount = { "Weekly": { amount: number, } } | { "Monthly": { amount: number, } } | { "Yearly": { amount: number, } } | { "EveryXYears": { x: number, amount: number, } };

export type BudgetCategory = { id: number, year: number, name: string, ignored: boolean, };

export type BudgetCategoryFields = { name: string, ignored: boolean, };

export type BudgetCloneRequest = { from_year: number, to_year: number, };

export type BudgetItem = { id: number, ignored: boolean, display_name: string, category_id: number, fund_id: number | null, name: string, amount: BudgetAmount | null, budget_only: boolean, };

export type BudgetItemFields = { category_id: number, fund_id: number | null, name: string, amount: BudgetAmount | null, budget_only: boolean, };

export type BudgetItemWithSpend = { year: number, spend: number, id: number, ignored: boolean, display_name: string, category_id: number, fund_id: number | null, name: string, amount: BudgetAmount | null, budget_only: boolean, };
