// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Expense = { id: number | null, account_id: number | null, transaction_date: string, transaction_time: string | null, description: string, amount: number, category_id: number | null, };
