// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetItemWithSpend } from "./Budget";

export type BudgetFund = { id: number, name: string, };

export type BudgetFundFields = { name: string, };

export type FundItems = { items: Array<BudgetItemWithSpend>, };

export type Funds = { funds: Array<BudgetFund>, };
