// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountClass } from "./AccountClass";

export type NewAccount = { name: string, class: AccountClass, statement_import_config_id: number | null, };
