// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AmountField = { "variant": "FromColumn", "params": { col: number, invert: boolean, skip_pattern: string | null, } } | { "variant": "FromCreditDebitColumns", "params": { first: number, invert_first: boolean, second: number, invert_second: boolean, } };

export type DateField = { "variant": "FromColumn", "params": { col: number, tz: TZ, } };

export type RecordMapping = { transaction_date: DateField, transaction_time: TimeField, description: TextField, amount: AmountField, };

export type TZ = "Local" | "UTC";

export type TextField = { "variant": "FromColumn", "params": { col: number, } };

export type TimeField = { "variant": "FromColumn", "params": { col: number, tz: TZ, } } | { "variant": "Empty" };
