// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpendingData = { data: Array<SpendingDataPoint>, };

export type SpendingDataPoint = { budget_item_id: number | null, month: string, amount: number, };
