// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetItemWithSpend } from "./Budget";

export type SpendingData = { data: Array<SpendingDataPoint>, fund_items: Array<BudgetItemWithSpend>, };

export type SpendingDataPoint = { budget_item_id: number | null, month: string, amount: number, };
